export const metadata = {
  title: {
    absolute: "Review",
  },
  description: "Generated by Res",
};
export default function ReviewLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {children}
      <footer>Test</footer>
    </>
  );
}
