import Navbar from "./components/Navbar/Navbar";
import "./global.css";
export const metadata = {
  title: {
    default: "Next.js App",
    template: "Next.js App - %s",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
